### ISSUE TITLE
Error from running "docker-compose -f docker-compose.prod.yml build"

### ISSUE THREAD

**Issue by momodou86** [ideacrew/hra_calculator#20]
``` bash
Step 21/23 : COPY . .
 ---> d7ca0f14bbfe
Step 22/23 : RUN yarn install && bundle exec rake assets:precompile
 ---> Running in 03922dd420e1
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > webpack-dev-server@3.8.1" has unmet peer dependency "webpack@^4.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.1" has unmet peer dependency "webpack@^4.0.0".
[4/4] Building fresh packages...
Done in 25.11s.
[dry-types] [] is mutable. Be careful: types will return the same instance of the default value every time. Call `.freeze` when setting the default or pass `shared: true` to discard this warning.
/app/config/application.rb:21:in `<top (required)>'
[dry-types] [] is mutable. Be careful: types will return the same instance of the default value every time. Call `.freeze` when setting the default or pass `shared: true` to discard this warning.
/app/config/application.rb:21:in `<top (required)>'
rake aborted!
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`
/bundle/gems/railties-6.0.0/lib/rails/application.rb:580:in `validate_secret_key_base'
/bundle/gems/railties-6.0.0/lib/rails/application.rb:423:in `secret_key_base'
/bundle/gems/devise-4.7.1/lib/devise/secret_key_finder.rb:24:in `key_exists?'
/bundle/gems/devise-4.7.1/lib/devise/secret_key_finder.rb:16:in `find'
/bundle/gems/devise-4.7.1/lib/devise/rails.rb:37:in `block in <class:Engine>'
/bundle/gems/railties-6.0.0/lib/rails/initializable.rb:32:in `instance_exec'
/bundle/gems/railties-6.0.0/lib/rails/initializable.rb:32:in `run'
/bundle/gems/railties-6.0.0/lib/rails/initializable.rb:61:in `block in run_initializers'
/bundle/gems/railties-6.0.0/lib/rails/initializable.rb:60:in `run_initializers'
/bundle/gems/railties-6.0.0/lib/rails/application.rb:363:in `initialize!'
/app/config/environment.rb:5:in `<main>'
/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/bundle/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:23:in `require'
/bundle/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/bundle/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/bundle/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/bundle/gems/railties-6.0.0/lib/rails/application.rb:339:in `require_environment!'
/bundle/gems/railties-6.0.0/lib/rails/application.rb:515:in `block in run_tasks_blocks'
/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/bundle/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/bundle/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/bundle/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/bundle/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/app/bin/bundle:104:in `load'
/app/bin/bundle:104:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)
ERROR: Service 'app' failed to build: The command '/bin/sh -c yarn install && bundle exec rake assets:precompile' returned a non-zero code: 1
```

**Comment by momodou86** [comment]
I ran into the above error when trying to setup the app using the production yaml file. I need some help to guide me pass this issue.

**Comment by matt--williams** [comment]
There is one Rails environment setup step that is not captured in the community site documentation, that is the generation of the Rails credentials.  For security reasons, we don't embed these in the repo and will expect each state to generate them for their specific implementation.  Please run this command in the root directory of the repository on your laptop or desktop.

```docker-compose run --rm runner rails credentials:edit```

On additional step for the production deployment is the creation of the TLS private keys and certificates.  The states will need to purchase CA certificates for production deployments, but for testing purposes, both locally and remote, self-signed certificates will suffice.  The docker file expects that these are in a folder one level up from the root directory of the repo.  This is done to ensure that certificates aren't accidentally pushed to a GitHub repo or Docker Hub (we don't want to solely rely on a .gitignore or .dockerignore to prevent the push given the sensitive nature of these files).  Simply make a 'certs' directory at the same level as the repository and add the private key and certificate using the following names.  These certificates will be added to the server at build time over a secure channel using Docker secrets.

``` 
hra_calculator>$ ls -ltr ../certs/
total 32
-rw-r--r--@ 1 matt-williams  staff  3790 Oct  3 11:01 fullchain.pem
-rw-------@ 1 matt-williams  staff  1704 Oct  3 11:01 privkey.pem
```

All of the information above will be added to the community site documentation soon.

**Comment by momodou86** [comment]
I have the same error even after trying the above

**Comment by matt--williams** [comment]
Please revisit the community site for updated instructions.  I've included commands to handle the credentials problem that lead to the original issue.

**Comment by DFos85** [comment]
@momodou86 we wanted to follow up to confirm how the installation is going. Are there any outstanding issues with standing up the application?
